tencent:
  secretId: "your-secret-id"
  secretKey: "your-secret-key"

domain:
  domain: "example.com"
  subDomain: "www"

checkInterval: 60

email:
  smtpServer: "smtp.example.com"
  smtpPort: 587
  username: "your-email@example.com"
  password: "your-email-password"
  recipient: "recipient@example.com"