tencent:
  secretId: "xxxxxxxxxxxxxxx"
  secretKey: "xxxxxxxxxxxxxxxxxx"

domain:
  domain: "xxxxx.com"
  subDomain: "xxx"

checkInterval: 600

email:
  smtpServer: "smtp.example.com"
  smtpPort: 587
  username: "your-email@example.com"
  password: "your-email-password"
  recipient: "recipient@example.com"

proxy:
  enableHTTP: true
  httpListenAddr: ":80"
  httpTargetAddr: "http://localhost:82"
  
  enableHTTPS: false
  httpsListenAddr: ":443"
  httpsTargetAddr: "http://localhost:8443"
  certFile: "/path/to/cert.pem"
  keyFile: "/path/to/key.pem"